// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

// Package cloudsearchdomainiface provides an interface for the Amazon CloudSearch Domain.
package cloudsearchdomainiface

import (
	"github.com/gosemver/aws_aws-sdk-go_v1.4.3-1-g1f24fa1/aws/request"
	"github.com/gosemver/aws_aws-sdk-go_v1.4.3-1-g1f24fa1/service/cloudsearchdomain"
)

// CloudSearchDomainAPI is the interface type for cloudsearchdomain.CloudSearchDomain.
type CloudSearchDomainAPI interface {
	SearchRequest(*cloudsearchdomain.SearchInput) (*request.Request, *cloudsearchdomain.SearchOutput)

	Search(*cloudsearchdomain.SearchInput) (*cloudsearchdomain.SearchOutput, error)

	SuggestRequest(*cloudsearchdomain.SuggestInput) (*request.Request, *cloudsearchdomain.SuggestOutput)

	Suggest(*cloudsearchdomain.SuggestInput) (*cloudsearchdomain.SuggestOutput, error)

	UploadDocumentsRequest(*cloudsearchdomain.UploadDocumentsInput) (*request.Request, *cloudsearchdomain.UploadDocumentsOutput)

	UploadDocuments(*cloudsearchdomain.UploadDocumentsInput) (*cloudsearchdomain.UploadDocumentsOutput, error)
}

var _ CloudSearchDomainAPI = (*cloudsearchdomain.CloudSearchDomain)(nil)
