// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package ses

import (
	"github.com/gosemver/aws_aws-sdk-go_v1.4.3-1-g1f24fa1/private/waiter"
)

func (c *SES) WaitUntilIdentityExists(input *GetIdentityVerificationAttributesInput) error {
	waiterCfg := waiter.Config{
		Operation:   "GetIdentityVerificationAttributes",
		Delay:       3,
		MaxAttempts: 20,
		Acceptors: []waiter.WaitAcceptor{
			{
				State:    "success",
				Matcher:  "pathAll",
				Argument: "VerificationAttributes.*.VerificationStatus",
				Expected: "Success",
			},
		},
	}

	w := waiter.Waiter{
		Client: c,
		Input:  input,
		Config: waiterCfg,
	}
	return w.Wait()
}
