// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

// Package mobileanalyticsiface provides an interface for the Amazon Mobile Analytics.
package mobileanalyticsiface

import (
	"github.com/gosemver/aws_aws-sdk-go_v1.4.3-1-g1f24fa1/aws/request"
	"github.com/gosemver/aws_aws-sdk-go_v1.4.3-1-g1f24fa1/service/mobileanalytics"
)

// MobileAnalyticsAPI is the interface type for mobileanalytics.MobileAnalytics.
type MobileAnalyticsAPI interface {
	PutEventsRequest(*mobileanalytics.PutEventsInput) (*request.Request, *mobileanalytics.PutEventsOutput)

	PutEvents(*mobileanalytics.PutEventsInput) (*mobileanalytics.PutEventsOutput, error)
}

var _ MobileAnalyticsAPI = (*mobileanalytics.MobileAnalytics)(nil)
