// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package elastictranscoder

import (
	"github.com/gosemver/aws_aws-sdk-go_v1.4.3-1-g1f24fa1/private/waiter"
)

func (c *ElasticTranscoder) WaitUntilJobComplete(input *ReadJobInput) error {
	waiterCfg := waiter.Config{
		Operation:   "ReadJob",
		Delay:       30,
		MaxAttempts: 120,
		Acceptors: []waiter.WaitAcceptor{
			{
				State:    "success",
				Matcher:  "path",
				Argument: "Job.Status",
				Expected: "Complete",
			},
			{
				State:    "failure",
				Matcher:  "path",
				Argument: "Job.Status",
				Expected: "Canceled",
			},
			{
				State:    "failure",
				Matcher:  "path",
				Argument: "Job.Status",
				Expected: "Error",
			},
		},
	}

	w := waiter.Waiter{
		Client: c,
		Input:  input,
		Config: waiterCfg,
	}
	return w.Wait()
}
